--- 
language: ruby
cache: bundler
rvm:
- 2.2.5
- 2.3.3
matrix:
  exclude:
    - rvm: 2.2.5
      env: TASK=coffeelint
    - rvm: 2.2.5
      env: TASK=rails_best_practices
    - rvm: 2.2.5
      env: TASK=rubocop
    - rvm: 2.2.5
      env: TASK=spec DB=mysql
    - rvm: 2.2.5
      env: TASK="spec spec:postgres" DB=postgresql
    - rvm: 2.2.5
      env: TASK=spec:javascript
    - rvm: 2.2.5
      env: TASK=container:spec
env:
  global:
    - DISPLAY=:99.0
  matrix:
    - TASK=coffeelint
    - TASK=rails_best_practices
    - TASK=rubocop
    - TASK=spec
    - TASK=spec DB=mysql
    - TASK="spec spec:postgres" DB=postgresql
    - TASK=spec:javascript
    - TASK=container:spec
before_install:
- sh -e /etc/init.d/xvfb start
- if [ "$DB" == 'mysql' ]; then echo "gem 'mysql2', '~> 0.3.13'" >> Gemfile; fi
install: bundle install --jobs=4
before_script:
- if [ -n "$DB" ]; then cp config/database.yml.$DB config/database.yml; fi
- bundle exec rake db:create db:migrate
sudo: required
addons:
  postgresql: "9.4"
  apt:
    packages:
      - libgmp-dev
services:
  - docker
  - mysql
script: bundle exec rake $TASK
notifications:
  slack:
    secure: xe6V8beAfRDNcyJFEY1Gn0diRTiXCmNmvdKkAM0Ft5T7RSqDAtFtumPvRs03Esn66FfqGqdjqa7BsTURBrf40t+shkF3Ab5AfHkNys/rCYnboGwdyUUAOIhWBl64Yjv7DzHW6AWWrTBqSDmeTGC3vX/FUwAHwcmyagBVurSoT5w=
branches:
  except:
    - deploy
